dist: xenial
language: python


cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  - py.test
after_success:
  - coveralls


jobs:
  include:
    - stage: test
      python: "3.6"

    - stage: docker
      services: [docker]
      env:
        - IMAGE_NAME=praekeltfoundation/dataplatform_sync
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "NR8oUMQ7rmdKv6WKf0qcX8dRkvJeyrxkz8W6AcaAKROIS3dPY9QZjmxCmpSfv56qBNBfSJn54yI0Vntf4mdF9DDOBHv1JtH7pES47u2DLYctSCMZ1Ww48gWsSw+55N4uFT6uNf6RZaTB3jneVNwyujGp19IavqfdlY1qgytD0hfrJhs2Wzk5+wOSzJ+5Je0Dxv8z/lldkweu4G5Vz318MmqBOCCK/zOjUWU0OLJIUaHywARxkFYoM3FB89cKGl0h4xKcdh4PVBinubhrpSRK6sWOqiTFU6bfulKeLAz7fL8FU0vKJ+CuTa9Tawn6pRrA+NcC1EjQSEFi43krUtT+lvhPE2odF2HLe40YAdCvxupi7houqh2231tz7nTtmLyTyOlI2OvVEV+CK+QMZwnMJCTT+XSGQLml7OWRUOx8mkblyIMEoAn3OcxkroMG9K7qKlgUGgLvDdnW+R23EZHqZgi9iTj3A+7kq13zdBX7QSpPFJYpLVU6Xi85IRvugzM7elw6mSV5V4n38xO6Vn4OJ2vz6DedEIFkEDDkxXgukT0/hg9Yrgsg9jY3EqnHA+0/NvoV2BuqtDtKGDAZ6QAFp/ea0nIZ4KlKPDfsO8IAmnNuGIxws4Ha4t56VIJx2M4zA7iKYoVi9RLqX5/yumEIDX1+8q/y7uu3mNAxSugJeTg="

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      after_success: []
