dist: xenial
language: python
python: "3.6"
addons:
  apt:
    packages:
    - sshpass

cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  - py.test
after_success:
  - coveralls


jobs:
  include:
    - stage: test

    - stage: docker
      services: [docker]
      env:
        - IMAGE_NAME=girleffect/dataplatform_sync
        - REGISTRY_USER=geautomation
        - secure: "7vDq2sGYOZtQDa14ko2Z0Sdw5N3cn4VxMPqQZnj9Rrp0cFdVIjFkH2SXHcj6Mai6zoTSGRjUyljPKrIKRSKb0HVyTXoahkFVeEqjRuNnVMhxCppjww/q4C0MkbIclXEHjFvNcpYIL6bDONibsfRb1AAfoQEHzTItjNRiLcZ+VlxIeDo7TJaM7sFxWTYfKnhZqLydm0PBIvVupQ+FSCZIIula0k26DOX1gYDdHfzfAp6OnV3KmtPFU5v1vRayf2Rx19NG7FNCP4MUQDo+XrS6EW9lvUxwU4SYZ6GLUPm67/11FjpfZPcHA/6zIDJJN0q4ZuP6Jyb1QEVinBcqcx+jIyuHidKDQ1NivsBrPynHHiiHJeb5QHLfUbb7PEpdXVwwaLJcELedOFR/ityVDJwqqukWZCNsSEmgziQ9NpnVx5JwkqbEW+VuoG6T+xEGYfgEkJirzIluwOXeaxRmjn0Ek1YUTJehFkrTut80/fVHbiAEm/hBMvURPf/RID7yKxQTEecH/GfWcqtPsX1ZkgsMS5kCezeGMJQokubbLMC1Gqojzq6UKZsdGvX7OgcIQxSKZpgtm1bjQV67OP1qnZacQX0hQ2DobrN8jnkXnP0b/YjVu1iA2sjdl9zKR7maqJ+KWCiV+4ptxZHEN8J+AWWhMGu6UOH/jXXacoGyAQgBGjo="

      script:
        - docker build --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      install: []
      after_success: []
