dist: xenial
language: python
python: "3.6"
addons:
  apt:
    packages:
    - sshpass

cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  - py.test
after_success:
  - coveralls


jobs:
  include:
    - stage: test

    - stage: docker
      services: [docker]
      env:
        - IMAGE_NAME=girleffect/dataplatform_sync
        - REGISTRY_USER=geautomation
        - secure: "kLP+MDzHhvy6/8WhmATuRZKbyhBbGdtOZzQo+4yH+lfqPwmacmSxyc0nqYk6TLI3LG12FY8MyAcnnB1PV9ydQoT27oqxu6uF9h3Jowz//TdfPWjzTV0b6WsPOmYsXgi7+da27yp0He2Pk/TOIAtAU5AO43WHqPI2Xq9BfXLFg256D5qcopKQmLqBBK/oSteIeJ3tU/QIIGFSbbf4NEf2j2/WiHmQFYXu4CNTGIsHwt0OZpxiKn9dA10gWq3dV4anO6LRVJBa9CXbTrfCW30S8SvTNSg3MHm1UTLg+NIYb627c65mt+ugAitK/4C+lNXuba2V8z3B/HLiXUtvGCe3vahFFp2SAFpvzGhPwFHdavajy42nTGDon73WbEB9SBgHSB/VlfB+xoGZaMAtPJrKSnaKgfgqoVM8vyTS5feU1sx2UaIG8UyxiFEeOIuD7DsNtObf6U0uS9EHYpUizA399Uo4RUwuBrK+SBoPray5ac+U2/b+Bd2myp0oMLzQVM/LqW2hP6Amy6VAWBZYlWT1xZGgDfQSzkr5elQwX3OvVweIStL/eN4rz9vjR2HggUBbX3DUHlnlJJJUf+nv88NCGKcZcF+dHjXG2VmMlavrx57hyvUbLtoQl1+dtnjVoaFRYB0VKf6AKMoMGvDsST2oaVcNJudESrrHijpev7otMoE="

      script:
        - docker build --tag "$IMAGE_NAME" .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - echo -n $REGISTRY_PASS | docker login -u "$REGISTRY_USER" --password-stdin
      deploy:
        - provider: script
          script: dcd --version "$(git rev-parse --short HEAD)" --version-latest "$IMAGE_NAME"
          on:
            branch: develop
        - provider: script
          script: dcd --tag "$TRAVIS_TAG" -- "$IMAGE_NAME"
          on:
            tags: true

      # Built steps inherited from the default stage that we don't want
      before_install: ignore
      install: []
      after_success: []
